### PR TITLE
Groups codes by pairs or threes depending on character count

### PR DESCRIPTION
**Pull request by beaucollins**
Purely an opinion but I find it easier to read two groups of three digits vs three groups of two digits.

And for 8 digit length codes I would say two groups of four digits would be better than four groups of two digits.

This change groups any code divisible by three into groups of three, divisible by two in pairs, otherwise no groupings.

img_1ee0ac437151-1

### CODE REVIEW

**Comment by mide** [comment]
That's a clever and elegant solution. 👍

**Comment by ghost** [comment]
I much prefer this over the always-by-twos approach that currently exists.

**Comment by jansenfuller** [comment]
Is there a particular reason why this has been shelved?

**Comment by beaucollins** [comment]
@jansenfuller  I think it just needs to be brought to the attention of @mattrubin

**Comment by mattrubin** [comment]
I'm sorry for the long delay in addressing this issue!

After much thought, I've opened [a new PR](https://github.com/mattrubin/Authenticator/pull/290) which adds a settings screen that allows the user to choose whether they prefer passwords rendered in groups of two digits or groups of three. I'd love to hear feedback from all the folks who prefer groups of three on whether this new approach feels like a satisfactory solution.

**Comment by mattrubin** [comment]
This PR has been superseded by #290. Thank you to @beaucollins for this proposal!

**Pull request closed without merging**
