### PR TITLE
Add explanation of backup/sync limitations

### LINKED ISSUE #145: Inform new users about backup limitations
By design, Authenticator stores tokens in the device's local keychain, which does not sync between devices. Apple only backs up these keychain items in an encrypted iTunes backup, so some users (#82, #133) who get new phones and restore from iCloud backups have lost their tokens.

Until a secure [backup and restore](https://github.com/mattrubin/Authenticator/issues/6) solution is implemented, new users should be informed of the limitations of backup and lack of syncing. It's not a complete solution, but it will hopefully prevent the unpleasant surprise of discovering one's tokens are unexpectedly gone.

### PR DESCRIPTION
**Pull request by mattrubin**
Inform new users about the limitations on backups and lack of syncing by adding a note to the main screen before the user adds any tokens, and linking to a more detailed explanation.

The contents of the backup info screen can be previewed here: https://rawgit.com/mattrubin/Authenticator/backup-warning/Authenticator/Resources/BackupInfo.html

I expect it will take several iterations to arrive at text which can make the technical details and security reasons clear to an average user.

Closes #145.

### CODE REVIEW

**Comment by mattrubin** [comment]
@beaucollins: I'd appreciate your feedback on both the content and the presentation of this info.

**Comment by beaucollins** [comment]
I think the text does a good job of explaining why secrets are not synced and why Authenticator has made that decision.

Worth noting is that it would take more than knowing your iCloud password to access iCloud Keychain items:

> Syncing your secret tokens to other devices via iCloud would invalidate the posession factor: an attacker who knew your iCloud password could steal your secret tokens without having physical access to your phone. 

In order to add another device to access iCloud Keychain the user is required to authorize the new device with an existing approved device. I don't know the ins and outs of the encryption Apple has implemented here but I think as this text stands it presents iCloud Keychain as less secure than it actually is.

If we want to get pedantic this part doesn't account for HOTP's but in practice I haven't come across any services that use it:

> When you use Authenticator to log in, it uses that secret and the current time to generate a unique password.

**Comment by mattrubin** [comment]
@beaucollins Thanks for the feedback!

I updated the wording of the section which previously referred to iCloud, to hopefully indicate the way in which cloud-based syncing and backup breaks the two-factor security model without implying specific risks with iCloud.

As for the second quote you mentioned: I did consider HOTPs when writing this, but as I've never encountered one myself, I suspect most users will never need to understand the distinction, and I decided to avoid introducing confusion by mentioning them. (I decided early on to not add analytics to Authenticator for privacy reasons, but I admit I'd love to get some statistics on what percentage of users – if any – are actually using HOTPs.)

**Comment by beaucollins** [comment]
> I admit I'd love to get some statistics on what percentage of users – if any – are actually using HOTPs.

To test parts of the app I started image searching for QR codes and found a few counter based images floating around.

I'm worried about how many two factor QR codes there were available. I want to believe they're all fake/example ones.

**Pull request merged**
