### PR TITLE
Reduce CPU load by reducing view update frequency

### PR DESCRIPTION
**Pull request by mattrubin**
Based on the excellent work by @beaucollins in PR #224. My changes on top of that PR can be seen [here](https://github.com/mattrubin/Authenticator/compare/188bf47...performance-refactor).

---

 Currently, the app animates the progress ring and keeps token passwords up-to-date by using `CADisplayLink` to regenerate the view model and update the view at 60 frames per second. This is needlessly inefficient, and [causes excessive processor load](https://github.com/mattrubin/Authenticator/issues/218). Instead of updating the view every frame, it is sufficient to generate a new view model only when a token password has updated, and to use Core Animation to drive the progress ring.

### Animatable Progress Ring

The drawing code for `OTPProgressRing` has been moved to a custom `CALayer` with an animatable `progress` property. The `TokenListViewModel`'s `ringProgress` property has been replaced with a `ProgressRingViewModel` which specifies the start and end times of the current cycle of the animation. These values are used to configure a `CABasicAnimation` which drives the ring animation, removing the need for constant updates from a `CADisplayLink`. The progress ring now only needs to be updated with a new view model when a new cycle of the animation should begin.

### View Model Expiration Date

The method which generates a view model for the token list (and for the root component) now returns a tuple containing both the view model and a `nextRefreshTime`. The `AppController`'s display link has been replaced with a refresh timer, which is configured to fire at the `nextRefreshTime` and trigger an update of the view with a new view model.

The app also now triggers a view update on `applicationWillEnterForeground`, to ensure the UI is up-to-date when the app returns from the background.

### Future Performance Considerations

These changes reduce idle CPU usage from around 40%  to less than 10%. The remaining CPU load is almost entirely caused by animating and redrawing the progress ring. Ideas for optimizing the drawing of the progress ring are [discussed below](https://github.com/mattrubin/Authenticator/pull/231#issuecomment-342622266).

### CODE REVIEW

**Comment by beaucollins** [comment]
I was considering using two `CAShapeLayer` instances to show the rings.

My assumption is that it will cut the work in half since it only calculates one path per progress change instead of two:

- `ProgressLayer`: child layers
  - `CAShapeLayer` - partial ring, changes with progress change
  - `CAShapeLayer` - full ring, only changes if the size of the view changes

**Comment by mattrubin** [comment]
@beaucollins That sounds like a good idea for optimizing the draw call. After commenting out the draw implementation, it does seem like some of the CPU load is caused just by the CAAnimation updating the progress property, so we may not be able to get this below 3-4%.

Thank you for all your work on this!

**Comment by beaucollins** [comment]
I gave the multiple layer idea a go and the CPU usage didn’t change noticeably.

Probably can’t squeeze much more out of it.

Changes look great.

**Review by beaucollins — APPROVED** [review]

**Comment by beaucollins** [comment]
So it looks like using a couple of `CAShapeLayer`s to draw the rings dropped the CPU to 1% on my simulator. **But** the `CABasicTransition` stopped updating the `progress` property value. It correctly triggered display updates for the animation frames but the progress property itself wouldn’t change.

**Pull request merged**
